on:
  push:
    braches:
      - release
    tags:
      - "*.*.*.*-rc.*"

jobs:
  merge-release-to-develop:
    runs-on: ubuntu-latest
    name: merge release to develop
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: release
          target_branch: develop
          github_token: ${{ github.token }}