name: New Release Candidate Workflow

# only trigger on release branch and tag patterns matches
# *.*.*.*-rc.*
on:
  push:
    braches:
      - release
    tags:
      - "*.*.*.*-rc.*"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: michaelw90/PHP-Lint@master

  merge-release-to-develop:
    needs: lint
    runs-on: ubuntu-latest
    name: merge release to develop
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'develop'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'