name: New Point Release Workflow

# only trigger on master branch and tag patterns matches
# *.*.*.*
on:
  push:
    braches:
      - master
    tags:
      - "[1-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: michaelw90/PHP-Lint@master

  merge-master-to-release:
    needs: lint
    runs-on: ubuntu-latest
    name: merge master to release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'release'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

  merge-release-to-develop:
    needs: merge-master-to-release
    runs-on: ubuntu-latest
    name: merge release to develop
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: merge
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: 'release'
          target_branch: 'develop'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

  phpmetrics-action:
    runs-on: ubuntu-latest
    name: PhpMetrics Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PhpMetrics Scan
        uses: umutphp/phpmetrics-action@v1
        with:
          folder: "./src"

      - name: Upload HTML Report
        uses: actions/upload-artifact@v1
        with:
          name: HTML Report
          path: phpmetrics.html
      - name: Upload XML Report
        uses: actions/upload-artifact@v1
        with:
          name: HTML Report
          path: phpmetrics.xml
      - name: Upload Violations Report
        uses: actions/upload-artifact@v1
        with:
          name: HTML Report
          path: violations.xml