name: New Point Release Workflow

# only trigger on master branch and tag patterns matches
# *.*.*.*
on:
  push:
    braches:
      - master
    tags:
      - "[1-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:

  merge-master-to-release:
    runs-on: ubuntu-latest
    name: merge master to release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'release'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

  merge-release-to-develop:
    runs-on: ubuntu-latest
    name: merge release to develop
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: 'release'
          target_branch: 'develop'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'